server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
    # hostname: localhost # eureka服务端的实例名称
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，不需要检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址用于查询服务和注册服务
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/