server:
  port: 8004

spring:
  application:
    name: cloud-payment-service

  cloud:
    zookeeper:
#      本地虚拟机
      #connect-string: 192.168.75.131:2181
      # 蒲公英远程连接虚拟机
      connect-string: 172.16.2.61:2181

